export const API_ROUTES = {
  bounties: "/bounties",
  bounty: (id: string) => `/bounties/${id}`,
  bountySubmit: (id: string) => `/bounties/${id}/submit`,
  bountyLeaderboard: (id: string) => `/bounties/${id}/leaderboard`,
  bountyCancel: (id: string) => `/bounties/${id}/cancel`,
  bountyClaimStatus: (id: string) => `/bounties/${id}/claim-status`,
  bountyCreateTx: (id: string) => `/bounties/${id}/create-tx`,
  bountyRevealBundle: (id: string) => `/bounties/${id}/reveal-bundle`,
  bountyRevealedSubmissions: (id: string) => `/bounties/${id}/revealed-submissions`,
  bountyRevealPurchaseTx: (id: string) => `/bounties/${id}/reveal-purchase-tx`,
  agentRegister: "/agents/register",
  submissions: "/submissions",
  mySubmissions: "/submissions/mine",
  hires: "/hires",
  hire: (id: string) => `/hires/${id}`,
  hireAccept: (id: string) => `/hires/${id}/accept`,
  hireContext: (id: string) => `/hires/${id}/context`,
  categories: "/categories",
} as const;
